xtuml/otel2puml

.devcontainer/devcontainer.json, tel2puml/puml_graph/graph.py, tests/tel2puml/puml_graph/test_graph.py
PR to fix bug in which `break` line was not added to PUML if the event types are altered after initialisation
Also removed reference to erebus in setting of pythonpath in devcontainer
=> 6 break not added to event if set outside init

.devcontainer/devcontainer.json, .github/workflows/test-workflow.yml, README.md
Explores how to install via pip instead of using anaconda. 
- Macos works fine as there is an up to date wheel for cvxopt1.3.2
- linux needs pre-requisites and some flags set for pip install
Updated:
- devcontainer to use linux
- github workflow to test all supported installations
- README updated to account for install options
=> 33 update to use only pip to install

docs/development/design/3-DN-Retrieving_unique_graphs_from_Otel_data/json_data_converter_HOWTO.md
This PR adds a HOWTO guide on how to configure json_data_converter using a config.yaml file.
=> 41-create-documentation-for-json_data_converter-module

tel2puml/find_unique_graphs/otel_ingestion/json_data_converter.py, tests/tel2puml/find_unique_graphs/test_json_data_converter.py
This PR updates json_data_converter:
- Updated type hints
- Split navigate_segment function into navigate_list and navigate_dict.
- Add build_nested_dict function to extract_nested_value function.
Tests have been written for the following functions:
- navigate_dict
- navigate_list
- extract_simple_value
- extract_value_from_path
- update_header_dict
- build_nested_dict
=> Add tests processing headers json data converter

tel2puml/find_unique_graphs/find_unique_graphs.py, tests/tel2puml/find_unique_graphs/conftest.py, tests/tel2puml/find_unique_graphs/test_find_unique_graphs.py
PR that provides functionality to get root nodes in batches using event ids of all root nodes stored in a temporary table.
=> 76 function to get root nodes

tests/tel2puml/find_unique_graphs/test_json_data_converter.py
This PR adds tests to the following functions to handle processing headers within json data converter:
- process_header
- extract_nested_value
=> Add tests for process header and extract nested values

tel2puml/sequence_otel_v2.py, tests/tel2puml/test_sequence_otel_v2.py
PR to implement a function that orders groups of OTelEvents by start timestamp using the earliest start timestamp of each group
=> 55 function to order groups of otelevent by start timestamps

tel2puml/otel_to_pv/config.py, tel2puml/otel_to_pv/data_sources/json_data_source/json_jq_converter.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/conftest.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/test_json_jq_converter.py
This PR adds functionality for parsing the JSON so that a priority order can be setup for key paths (if they produce a null result evaluate the next value).
Also adds in error catching for setting variables in the JQ query, defaulting to null if there is a problem with the pathing to the variable
=> 103 provide functionality for fallback values in jq parsing

tel2puml/sequence_otel_v2.py, tests/tel2puml/test_sequence_otel_v2.py
This PR adds an interface within the otel sequencer module that takes in a generator of generator of OTelEvents and returns a generator of generator of PVEvents.
=> 105-interface-for-sequencer-to-ingest-stream-of-streams-of-otelevent

tel2puml/otel_to_pv/sequence_otel_v2.py, tests/tel2puml/otel_to_pv/test_sequence_otel_v2.py
This PR adds a function otel_to_pv that takes in the config, streams data from the data holder and converts OTelEvents to PVEvents.
=> 116-function-to-take-config-and-produce-pv-events-grouped-by-job-name

tel2puml/otel_to_pv/config.py, tel2puml/otel_to_pv/otel_to_pv.py, tel2puml/otel_to_pv/otel_to_pv_types.py, tel2puml/otel_to_pv/sequence_otel.py, tests/tel2puml/otel_to_pv/test_config.py, tests/tel2puml/otel_to_pv/test_otel_to_pv.py, tests/tel2puml/otel_to_pv/test_otel_to_pv_types.py, tests/tel2puml/otel_to_pv/test_sequence_otel.py
PR to add functionality to change OTelEvents ingested based on their children.
- Updates config to provide information on event types that need changing
- Updates otel_to_pv to use the config provided
- Updates sequencer to use event types along with mapping information
=> 143 option to map event type name to another name given children

tel2puml/otel_to_pv/data_holders/sql_data_holder/sql_dataholder.py, tests/tel2puml/otel_to_pv/conftest.py, tests/tel2puml/otel_to_pv/data_holders/sql_data_holder/test_sql_dataholder.py
Fixes bug in which if an event has no root event then an SQL null constraint error occurs.
=> 154 fix update job names by root span

tel2puml/otel_to_pv/data_holders/sql_data_holder/sql_dataholder.py, tests/tel2puml/otel_to_pv/data_holders/sql_data_holder/test_sql_dataholder.py
Fixes bug in which child event ids (not a required field) were being used to update node relations table. this has been fixed in this PR to use only parent_event_id field that should always be present.
=> 152 fix data holder node relation addition

tel2puml/otel_to_pv/data_holders/base.py, tel2puml/otel_to_pv/data_holders/sql_data_holder/sql_dataholder.py, tel2puml/otel_to_pv/otel_to_pv.py, tests/tel2puml/otel_to_pv/data_holders/sql_data_holder/test_sql_dataholder.py, tests/tel2puml/otel_to_pv/test_otel_to_pv.py
This PR adds a method to the DataHolder and SQLDataholder class to remove spans associated with job ids that have disconnected spans.
=> 158-function-to-remove-jobs-with-disconnected-spans

tel2puml/otel_to_pv/sequence_otel.py, tests/tel2puml/otel_to_pv/test_sequence_otel.py
Added check for consistency when building job dicts of otel events
=> 160 - update sequencer to throw away trees that are disconnected

tel2puml/otel_to_pv/data_sources/json_data_source/json_datasource.py, tel2puml/otel_to_pv/data_sources/json_data_source/json_jq_converter.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/conftest.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/test_json_datasource.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/test_json_jq_converter.py
This PR introduces functionality that skips over validation errors but reports them in logging. 
Also adds a pbar for:
- number of files processed
- number of validation errors seen
=> 166 add logging for validation fails for otel events

tel2puml/__main__.py, tel2puml/otel_to_puml.py, tel2puml/otel_to_pv/otel_to_pv.py, tel2puml/tel2puml_types.py, tests/tel2puml/otel_to_puml/test_otel_to_puml.py
This PR extends otel_to_puml to use save_events and output_folder_directory that are now used in pv_to_puml.
=> 169 update otel to puml with save_events

tel2puml/puml_graph.py, tests/tel2puml/puml_graph/test_puml_graph.py
When writing a uml block for a PUMLKillNode the incorrect statement was used, `kill`, whereas plus2json only supports `detach` for these cases
=> 171 replace kill with detach

tel2puml/otel_to_pv/data_holders/base.py, tests/tel2puml/otel_to_puml/conftest.py, tests/tel2puml/otel_to_pv/conftest.py, tests/tel2puml/otel_to_pv/data_holders/sql_data_holder/test_sql_dataholder.py, tests/tel2puml/otel_to_pv/data_holders/test_base_data_holder.py, tests/tel2puml/otel_to_pv/test_ingest_otel_data.py
PR to update how min and max timestamps are used on dataholder i.e. if the dataholder is full but no data was ingested the timestamps would make no sense
=> 173 dataholder default max and min timestamp wrong way round

docs/user/Config.md, docs/user/json_data_converter_HOWTO.md, tel2puml/__main__.py, tel2puml/otel_to_pv/config.py, tel2puml/otel_to_pv/data_holders/sql_data_holder/sql_dataholder.py, tel2puml/otel_to_pv/data_sources/data_sources_config.py, tel2puml/otel_to_pv/data_sources/json_data_source/json_config.py, tel2puml/otel_to_pv/data_sources/json_data_source/json_datasource.py, tel2puml/otel_to_pv/data_sources/json_data_source/json_jq_converter.py, tel2puml/otel_to_pv/ingest_otel_data.py, tel2puml/otel_to_pv/otel_to_pv.py, tests/tel2puml/otel_to_puml/conftest.py, tests/tel2puml/otel_to_puml/test_otel_to_puml.py, tests/tel2puml/otel_to_pv/conftest.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/conftest.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/test_json_config.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/test_json_datasource.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/test_json_jq_converter.py, tests/tel2puml/otel_to_pv/test_config.py, tests/tel2puml/otel_to_pv/test_ingest_otel_data.py, tests/tel2puml/otel_to_pv/test_otel_to_pv.py
PR to update JSON config to be able to use input jq query string. 
Also updates the following:
- For strictness of config use almost everything now uses PyDantic BaseModel to ensure correct usage of config fields for user
- Ensures a user can provide just a single string to `key_paths` in a FieldSpec for the most basic of cases
=> 184 add option to use jq string query instead of field mapping

README.md, docs/user/mapping_config.md, tel2puml/__main__.py, tel2puml/mapping_config.yaml, tel2puml/otel_to_pv/otel_to_pv.py, tel2puml/pv_event_simulator.py, tel2puml/pv_to_puml/pv_to_puml.py, tel2puml/tel2puml_types.py, tests/tel2puml/otel_to_puml/test_otel_to_puml.py, tests/tel2puml/otel_to_pv/test_otel_to_pv.py, tests/tel2puml/test_pv_event_simulator.py
This PR introduces support for specifying a custom mapping_config.yaml file in the tel2puml CLI tool. It adds the ability to map application-specific data fields to PVEvent fields via the --mapping-config or -mc flag, ensuring flexibility when dealing with non-standard data structures.
=> 195-pv-conversion-using-schema

docs/user/Config.md, tel2puml/otel_to_pv/data_sources/json_data_source/json_config.py, tests/tel2puml/main/conftest.py, tests/tel2puml/otel_to_pv/conftest.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/test_json_config.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/test_json_datasource.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/test_json_jq_converter.py, tests/tel2puml/otel_to_pv/test_ingest_otel_data.py
PR to update the solution to make sure dirpath and filepath cannot be used in conjunction with one another for user experience
=> 219 config file validation when dirpath and filepath are both populated with valid entries

README.md, tel2puml/__main__.py
Fix  CLI help for pv to puml -fp option and file_paths option
Also updated information on `group-by-job` option to provide extra information.
=> 229 help text pv2puml the text cannot be used with file paths is missing

docs/user/e2e_walkthrough.md
This PR updates file and folder references in e2e_walkthrough.md so that it does not point towards a non-existent file. 
A note has been added to notify that the puml could be different layout, but flow should be the same.
=> 239 update e2e_walkthrough.md

README.md
Removes recommended text for devcontainer setup and adds notes just to use for development
=> 255 - updated README

README.md
PR to add note to README for docker image use
=> 261 - update README with note on folder creation
