xtuml/otel2puml

tel2puml/find_unique_graphs/config.yaml
This PR adds a find_unique_graphs folder and adds a config.yaml file with default configuration values.
=> 5 Add yaml config file

mypy_errors.txt, tel2puml/find_unique_graphs/otel_ingestion/otel_data_source.py
This PR creates an abstract base class OTELDataSource which creates iterable OTelEvent objects.
=> 4 Create OTELDataSource ABC (#22)

mypy_errors.txt, tel2puml/find_unique_graphs/otel_ingestion/otel_data_model.py
This PR creates a SQLAlchemy model NodeModel that represents a node within a graph. It has an association table that will be able to associate a parent node to its child nodes.
The association table will be populated if child_event_ids are present within the node data. Otherwise, we can infer relationships from the node's parent_event_id.
=> 10 Create NodeModel class

docs/development/design/3-DN-Retrieving_unique_graphs_from_Otel_data/DN_3_Retrieve_unique_graphs_from_Otel_data.md, tel2puml/find_unique_graphs/otel_ingestion/otel_data_holder.py
This PR adds an ABC DataHolder which will ingest OtelEvent objects and save them.
=> Create DataHolder ABC

docs/development/design/3-DN-Retrieving_unique_graphs_from_Otel_data/DN_3_Retrieve_unique_graphs_from_Otel_data.md, tel2puml/find_unique_graphs/find_unique_graphs.py, tests/tel2puml/find_unique_graphs/test_find_unique_graphs.py
PR to add the functionality to get the time window from a dataholder given a buffer in minutes.
=> 47 function to get time window

tel2puml/find_unique_graphs/config.yaml, tel2puml/find_unique_graphs/otel_ingestion/json_data_converter.py, tests/tel2puml/find_unique_graphs/conftest.py, tests/tel2puml/find_unique_graphs/test_otel_data_source.py
This PR fixes a bug when specifying HEADER attributes within the field_mapping config. It now correctly parses a list of HEADER attributes, which can be accessed within the field mapping.
Integration tests have been updated to check for this scenario.
=> 54-fix-header-bug-in-json_data_converter

tel2puml/find_unique_graphs/find_unique_graphs.py, tests/tel2puml/find_unique_graphs/test_find_unique_graphs.py
PR to add functionality to grab all nodes with a specific job id from the SQLDataHolder
=> 65 function to return nodes within batch

tel2puml/find_unique_graphs/find_unique_graphs.py, tests/tel2puml/find_unique_graphs/conftest.py, tests/tel2puml/find_unique_graphs/test_find_unique_graphs.py
PR to create a dictionary mapping event id to child node model given an input iterable of node model
=> 67 function to create dict of event id to child nodemodel

tel2puml/find_unique_graphs/find_unique_graphs.py, tel2puml/find_unique_graphs/otel_ingestion/otel_data_model.py, tests/tel2puml/find_unique_graphs/conftest.py, tests/tel2puml/find_unique_graphs/test_find_unique_graphs.py, tests/tel2puml/find_unique_graphs/test_otel_data_holder.py
PR to implement end to end find unique graphs with sql functionality.
Updates to JobHash model to include job_name column
=> 80 function to find unique graphs using sql

tel2puml/find_unique_graphs/otel_ingestion/json_data_converter.py, tests/tel2puml/find_unique_graphs/test_json_data_converter.py
This PR adds tests for processing spans within json data converter.
=> 78-tests-for-processing-spans-within-json-data-converter

tel2puml/sequence_otel_v2.py, tel2puml/utils.py, tests/tel2puml/test_sequence_otel_v2.py
PR for sequencing an input tree of otel events
=> 59 function to sequence an input tree of otelevent

tel2puml/sequence_otel_v2.py, tests/tel2puml/test_sequence_otel_v2.py
PR to produce `sequence_otel_jobs` that ties together all the sub-functions for sequencing PVEvents sequences form OTelEvent Trees
=> 60 function to sequence a stream of trees of otelevents into streams of pvevent sequences

tel2puml/find_unique_graphs/find_unique_graphs.py, tel2puml/find_unique_graphs/otel_ingestion/otel_data_holder.py, tests/tel2puml/find_unique_graphs/conftest.py, tests/tel2puml/find_unique_graphs/test_otel_data_holder.py
provides an abstracted interface for find unique graphs on the class DataHolder and subclasses.
=> 97 dataholder abstract method find unique graphs

tel2puml/otel_to_pv/data_holders/base.py, tel2puml/otel_to_pv/data_holders/sql_data_holder/sql_dataholder.py, tests/tel2puml/otel_to_pv/conftest.py, tests/tel2puml/otel_to_pv/data_holders/sql_data_holder/test_sql_dataholder.py
This PR extends the data holder base class with a stream_data method. SQLDataHolder is now able to stream OtelEvents from the database efficiently by using generator expressions, allowing for large datasets to be handled.
Tests have also been added to test functionality.
=> 102-interface-for-streaming-data-from-data-holder

.mypy.ini, tel2puml/otel_to_pv/otel_to_pv_types.py, tests/tel2puml/otel_to_pv/conftest.py, tests/tel2puml/otel_to_pv/data_holders/sql_data_holder/test_sql_dataholder.py, tests/tel2puml/otel_to_pv/test_otel_to_pv_types.py
PR to replace OTelEvent as pydantic model for validation and conversion purposes.
=> 107 otelevent as pydantic model

tel2puml/otel_to_pv/config.py
PR to update what types FieldSpec will accept
=> 110 - update types

tel2puml/otel_to_pv/config.py, tel2puml/otel_to_pv/data_sources/json_data_source/json_jq_converter.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/conftest.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/test_json_jq_converter.py, tests/tel2puml/otel_to_pv/test_config.py
PR to test functionality that converts FieldSpec to JQFieldSpec and validates inputs to check consistency
=> 113 function to convert fieldspec field mapping to jqfieldspec field mapping

tel2puml/otel_to_pv/data_holders/base.py, tel2puml/otel_to_pv/data_holders/sql_data_holder/sql_dataholder.py, tests/tel2puml/otel_to_pv/conftest.py, tests/tel2puml/otel_to_pv/data_holders/sql_data_holder/test_sql_dataholder.py
PR to provide functionality to set the job name to the job name of the root span
=> 126 provide functionality to get job name from root span of job id group

tel2puml/otel_to_puml.py, tel2puml/otel_to_pv/config.py, tel2puml/otel_to_pv/sequence_otel.py, tel2puml/tel2puml_types.py, tests/tel2puml/otel_to_puml/test_otel_to_puml.py, tests/tel2puml/otel_to_pv/test_config.py, tests/tel2puml/otel_to_pv/test_sequence_otel.py
PR to add `sequencer` config that contains the async_event_groups given per job name.
=> 135 add async events groups to config

tel2puml/otel_to_puml.py, tel2puml/otel_to_pv/config.py, tel2puml/otel_to_pv/otel_to_pv.py, tel2puml/otel_to_pv/sequence_otel.py, tests/tel2puml/otel_to_puml/test_otel_to_puml.py, tests/tel2puml/otel_to_pv/conftest.py, tests/tel2puml/otel_to_pv/test_config.py, tests/tel2puml/otel_to_pv/test_otel_to_pv.py, tests/tel2puml/otel_to_pv/test_sequence_otel.py
PR to add async flag to config
Also move otel_to_pv to own module file.
=> 137 add async flag to config

tel2puml/otel_to_pv/data_sources/json_data_source/json_datasource.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/test_json_datasource.py
PR adds non-strict parsing to JSON decoder
=> 139 add non strict parsing of json

tel2puml/otel_to_pv/otel_to_pv.py
Adds `DataHolder.update_job_names_by_root_span` into `otel_to_pv` workflow
=> 141 - add update_job_names_by_root_span call into process

tel2puml/otel_to_pv/data_sources/json_data_source/json_jq_converter.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/conftest.py, tests/tel2puml/otel_to_pv/data_sources/json_data_source/test_json_jq_converter.py
This PR updates tests to check for the following specific negative cases when searching arrays:
- When the searched for key value in the array is not present and there is a fallback value
- When the array that would be searched for does not exist
=> 156 fix json jq converter

tel2puml/otel_to_pv/data_holders/base.py, tel2puml/otel_to_pv/data_holders/sql_data_holder/sql_dataholder.py, tel2puml/otel_to_pv/otel_to_pv.py, tests/tel2puml/otel_to_puml/conftest.py, tests/tel2puml/otel_to_pv/conftest.py, tests/tel2puml/otel_to_pv/data_holders/sql_data_holder/test_sql_dataholder.py, tests/tel2puml/otel_to_pv/test_otel_to_pv.py
PR to remove events that are not within the time buffer. Has not removed this from unique graphs but this will be removed at a later point
=> 163 separate time buffer from find unique graphs function

tel2puml/puml_graph.py, tests/tel2puml/puml_graph/test_puml_graph.py
Plus2json only supports `case` statement with the next part brackets containing a string i.e. needed to change `case () -> case ("")`
=> 172 - updated test to use case ("") and updated functionality

.github/workflows/PythonLinting.yml, .github/workflows/test-workflow.yml, README.md, requirements.txt, scripts/install_repositories.sh, tel2puml/pv_event_simulator.py, tests/tel2puml/test_pv_event_simulator.py
This PR removes the dependency on test harness/erebus repository
=> 180 remove dependency on test harness

tel2puml/pv_to_puml/pv_to_puml.py, tests/tel2puml/otel_to_puml/test_otel_to_puml.py, tests/tel2puml/pv_to_puml/test_pv_to_puml.py
This PR fixes the group by job id functionality of pv_files_to_pv_streams which was incorrectly implmented.
=> 178 fix group by job id option

.github/workflows/build-push-arifacts.yml, .github/workflows/build-push.yml, README.md, tel2puml/__main__.py
This PR creates an executable python zip archive using zipapp and integrates it into the CICD workflow, creating a release for both amd and arm architectures.
=> 186-create-executable-python-zip-archive-using-zipapp

README.md, tel2puml/puml_graph.py
This PR makes the quick start example usage match all the input and output example data.
=> 190 - Update README for less ambiguous quick start usage

README.md
Update to move dependencies before installation off the back of user testing.
=> 189 - move dependencies higher up

README.md
This PR updates the README adding git clone instructions in the manual installation section.
=> 193 update readme with git clone instructions

tel2puml/otel_to_pv/data_holders/base.py, tel2puml/otel_to_pv/data_holders/sql_data_holder/data_model.py, tel2puml/otel_to_pv/data_holders/sql_data_holder/sql_dataholder.py, tests/tel2puml/otel_to_pv/data_holders/sql_data_holder/test_sql_dataholder.py
This PR ensures that duplicate spans cannot be added to the database and when there is an error these duplicates are filtered out and their number is reported in the logging.
=> 196 handle duplicate spans

tel2puml/otel_to_pv/data_holders/sql_data_holder/data_model.py
PR to fix performance degradation where NODE ASSOCIATION table primary keys were removed by mistake.
=> 199 - readded primary key fields as True

README.md
This PR adds min/max versions of python that can be used.
=> 204 add min-max versions of python that can be used to readme

docs/user/json_data_converter_HOWTO.md
PR to update incorrect title.
Also changes wording of introduction slightly.
=> 202 - updated title and introduction

docs/user/json_data_converter_HOWTO.md
PR to add quotation marks where required.
Also provided information on when and why to use quotation marks
=> 203 quotations missing from text and examples

tel2puml/pv_to_puml/walk_puml_graph/walk_puml_logic_graph.py, tests/tel2puml/pv_to_puml/walk_puml_graph/test_walk_puml_logic_graph.py
Bug fix in which is_loop_kill_path attribute was being set incorrectly causing issues further down the chain.
=> 210 fix setting of logic node loop kill paths

docs/user/json_data_converter_HOWTO.md
PR to update README to add in array indication for "spans" that matches actual data
=> 206 - added array indication in paths for "spans" that matches the data used

docs/user/Config.md
PR fix time buffer to actual default value used
=> 213 - change to actual default

docs/user/Config.md
=> 217 - add note on maintaining indentation

docs/user/json_data_converter_HOWTO.md
=> 218 - added note on indentation

tel2puml/otel_to_pv/data_holders/sql_data_holder/sql_dataholder.py, tests/tel2puml/otel_to_pv/data_holders/sql_data_holder/test_sql_dataholder.py
PR to ensure that when the __exit__ method is called that any non unique NodeModel (by event id) are filtered out
=> 223 handle duplicate spans for final batch

README.md, docs/user/DataTypes.md, docs/user/json_data_converter_HOWTO.md, docs/user/sequencer_HOWTO.md
PR to add README detailing datatypes and field meanings and hierarchical structure of data fields
=> 225 add readme file for description of datatypes used

tel2puml/__main__.py
Fixes typo in `-se` option text
=> 228 - fixed typo

tel2puml/pv_to_puml/pv_to_puml.py, tests/tel2puml/otel_to_puml/test_otel_to_puml.py, tests/tel2puml/pv_to_puml/test_pv_to_puml.py
This PR fixes a bug where the job name was not pulling through to the puml string.
Tests have been updated.
=> 234 Update job name handling in PUML conversion

README.md
This PR fixes link No 5 in the README.
=> 236 Fix link in readme

docs/development/design/3-DN-Retrieving_unique_graphs_from_Otel_data/DN_3_Retrieve_unique_graphs_from_Otel_data.md, docs/user/json_data_converter_HOWTO.md
This PR updates the timestamp data types within the docs to int.
=> 241 update docs timestamp data type to int

docs/user/sequencer_HOWTO.md
=> 246 - fixed linked to diagram

docs/user/json_data_converter_HOWTO.md
PR to remove inconsistent labelling in table of contents
=> 245 - removed inconsistent table of contents labeling

docs/user/json_data_converter_HOWTO.md
=> 244 - fixed link

README.md
Updates README to add note that config file needs updating for dirpath to reflect mounted path.
=> 256 - update README

README.md, tel2puml/__main__.py, tel2puml/pv_event_simulator.py, tel2puml/tel2puml_types.py, tests/tel2puml/main/test_main.py, tests/tel2puml/pv_to_puml/conftest.py, tests/tel2puml/test_tel2puml_types.py
This pull request refactors the error handling in the main script by adding a new function called `handle_exception`. This function handles exceptions with custom messaging and exit codes. It also includes a debug flag that can be used to enable debug mode that shows the full stacktrace.
=> 243 - Refactor error handling and add debug flag to main

.github/workflows/build-push-arifacts.yml, README.md, scripts/build_zip_app.sh, tel2puml/__main__.py, tel2puml/utils.py, tests/tel2puml/main/test_main.py
PR to update workflow to create working zipapp that is distributed with a release and installs requirements on host machine.
=> 259 fix zip app so pre requisites installed
